/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as TestTriggerRouteImport } from './routes/test/trigger'
import { Route as TestSmokeRouteImport } from './routes/test/smoke'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as ApiManualRunsRouteImport } from './routes/api/manual-runs'
import { Route as ShellActivateRouteImport } from './routes/_shell/activate'
import { Route as ApiDeviceAuthorizationsIndexRouteImport } from './routes/api/device-authorizations/index'
import { Route as ApiDeviceAuthorizationsPollRouteImport } from './routes/api/device-authorizations/poll'
import { Route as ApiDaemonsEnrollmentTokensRouteImport } from './routes/api/daemons/enrollment-tokens'
import { Route as ApiDaemonsEnrollRouteImport } from './routes/api/daemons/enroll'
import { Route as ApiDaemonsDaemonIdRouteImport } from './routes/api/daemons/$daemonId'
import { Route as ApiConfigurationsInstallRouteImport } from './routes/api/configurations/install'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AgentExecutionsExecutionIdMcpRouteImport } from './routes/agent-executions/$executionId/mcp'
import { Route as ApiIntegrationsSlackEventsRouteImport } from './routes/api/integrations/slack/events'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack/callback'
import { Route as ApiIntegrationsGithubSetupRouteImport } from './routes/api/integrations/github/setup'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api/integrations/github/callback'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport } from './routes/agent-executions/$executionId/attachments/$attachmentId'
import { Route as ShellOOrganizationSlugTeamRouteImport } from './routes/_shell/o/$organizationSlug/team'
import { Route as ShellOOrganizationSlugProjectsRouteImport } from './routes/_shell/o/$organizationSlug/projects'
import { Route as ShellOOrganizationSlugDaemonsRouteImport } from './routes/_shell/o/$organizationSlug/daemons'
import { Route as ShellOOrganizationSlugConnectionsRouteImport } from './routes/_shell/o/$organizationSlug/connections'
import { Route as ShellOOrganizationSlugApiKeysRouteImport } from './routes/_shell/o/$organizationSlug/api-keys'
import { Route as ShellOOrganizationSlugProjectsIndexRouteImport } from './routes/_shell/o/$organizationSlug/projects/index'
import { Route as ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/overview'
import { Route as ShellOOrganizationSlugProjectsProjectSlugExecutionsRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/executions'
import { Route as ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
import { Route as ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/activity'
import { Route as ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const TestTriggerRoute = TestTriggerRouteImport.update({
  id: '/test/trigger',
  path: '/test/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSmokeRoute = TestSmokeRouteImport.update({
  id: '/test/smoke',
  path: '/test/smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManualRunsRoute = ApiManualRunsRouteImport.update({
  id: '/api/manual-runs',
  path: '/api/manual-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellActivateRoute = ShellActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => ShellRoute,
} as any)
const ApiDeviceAuthorizationsIndexRoute =
  ApiDeviceAuthorizationsIndexRouteImport.update({
    id: '/api/device-authorizations/',
    path: '/api/device-authorizations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDeviceAuthorizationsPollRoute =
  ApiDeviceAuthorizationsPollRouteImport.update({
    id: '/api/device-authorizations/poll',
    path: '/api/device-authorizations/poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDaemonsEnrollmentTokensRoute =
  ApiDaemonsEnrollmentTokensRouteImport.update({
    id: '/api/daemons/enrollment-tokens',
    path: '/api/daemons/enrollment-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDaemonsEnrollRoute = ApiDaemonsEnrollRouteImport.update({
  id: '/api/daemons/enroll',
  path: '/api/daemons/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaemonsDaemonIdRoute = ApiDaemonsDaemonIdRouteImport.update({
  id: '/api/daemons/$daemonId',
  path: '/api/daemons/$daemonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigurationsInstallRoute =
  ApiConfigurationsInstallRouteImport.update({
    id: '/api/configurations/install',
    path: '/api/configurations/install',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExecutionsExecutionIdMcpRoute =
  AgentExecutionsExecutionIdMcpRouteImport.update({
    id: '/agent-executions/$executionId/mcp',
    path: '/agent-executions/$executionId/mcp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackEventsRoute =
  ApiIntegrationsSlackEventsRouteImport.update({
    id: '/api/integrations/slack/events',
    path: '/api/integrations/slack/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubSetupRoute =
  ApiIntegrationsGithubSetupRouteImport.update({
    id: '/api/integrations/github/setup',
    path: '/api/integrations/github/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute =
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport.update({
    id: '/agent-executions/$executionId/attachments/$attachmentId',
    path: '/agent-executions/$executionId/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShellOOrganizationSlugTeamRoute =
  ShellOOrganizationSlugTeamRouteImport.update({
    id: '/o/$organizationSlug/team',
    path: '/o/$organizationSlug/team',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugProjectsRoute =
  ShellOOrganizationSlugProjectsRouteImport.update({
    id: '/o/$organizationSlug/projects',
    path: '/o/$organizationSlug/projects',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugDaemonsRoute =
  ShellOOrganizationSlugDaemonsRouteImport.update({
    id: '/o/$organizationSlug/daemons',
    path: '/o/$organizationSlug/daemons',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugConnectionsRoute =
  ShellOOrganizationSlugConnectionsRouteImport.update({
    id: '/o/$organizationSlug/connections',
    path: '/o/$organizationSlug/connections',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugApiKeysRoute =
  ShellOOrganizationSlugApiKeysRouteImport.update({
    id: '/o/$organizationSlug/api-keys',
    path: '/o/$organizationSlug/api-keys',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugProjectsIndexRoute =
  ShellOOrganizationSlugProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugOverviewRoute =
  ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport.update({
    id: '/$projectSlug/overview',
    path: '/$projectSlug/overview',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute =
  ShellOOrganizationSlugProjectsProjectSlugExecutionsRouteImport.update({
    id: '/$projectSlug/executions',
    path: '/$projectSlug/executions',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute =
  ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport.update({
    id: '/$projectSlug/configuration',
    path: '/$projectSlug/configuration',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugActivityRoute =
  ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport.update({
    id: '/$projectSlug/activity',
    path: '/$projectSlug/activity',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute =
  ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport.update({
    id: '/$projectSlug/settings/general',
    path: '/$projectSlug/settings/general',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/activate': typeof ShellActivateRoute
  '/api/manual-runs': typeof ApiManualRunsRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/trigger': typeof TestTriggerRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/configurations/install': typeof ApiConfigurationsInstallRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/daemons/enrollment-tokens': typeof ApiDaemonsEnrollmentTokensRoute
  '/api/device-authorizations/poll': typeof ApiDeviceAuthorizationsPollRoute
  '/api/device-authorizations/': typeof ApiDeviceAuthorizationsIndexRoute
  '/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsRouteWithChildren
  '/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/o/$organizationSlug/projects/': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
  '/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/o/$organizationSlug/projects/$projectSlug/executions': typeof ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute
  '/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/activate': typeof ShellActivateRoute
  '/api/manual-runs': typeof ApiManualRunsRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/trigger': typeof TestTriggerRoute
  '/': typeof ShellIndexRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/configurations/install': typeof ApiConfigurationsInstallRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/daemons/enrollment-tokens': typeof ApiDaemonsEnrollmentTokensRoute
  '/api/device-authorizations/poll': typeof ApiDeviceAuthorizationsPollRoute
  '/api/device-authorizations': typeof ApiDeviceAuthorizationsIndexRoute
  '/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
  '/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/o/$organizationSlug/projects/$projectSlug/executions': typeof ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute
  '/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/_shell/activate': typeof ShellActivateRoute
  '/api/manual-runs': typeof ApiManualRunsRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/trigger': typeof TestTriggerRoute
  '/_shell/': typeof ShellIndexRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/configurations/install': typeof ApiConfigurationsInstallRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/daemons/enrollment-tokens': typeof ApiDaemonsEnrollmentTokensRoute
  '/api/device-authorizations/poll': typeof ApiDeviceAuthorizationsPollRoute
  '/api/device-authorizations/': typeof ApiDeviceAuthorizationsIndexRoute
  '/_shell/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/_shell/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/_shell/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/_shell/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsRouteWithChildren
  '/_shell/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/_shell/o/$organizationSlug/projects/': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/executions': typeof ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/webhook'
    | '/activate'
    | '/api/manual-runs'
    | '/assets/$'
    | '/test/smoke'
    | '/test/trigger'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/configurations/install'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/daemons/enrollment-tokens'
    | '/api/device-authorizations/poll'
    | '/api/device-authorizations/'
    | '/o/$organizationSlug/api-keys'
    | '/o/$organizationSlug/connections'
    | '/o/$organizationSlug/daemons'
    | '/o/$organizationSlug/projects'
    | '/o/$organizationSlug/team'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/o/$organizationSlug/projects/'
    | '/o/$organizationSlug/projects/$projectSlug/activity'
    | '/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/o/$organizationSlug/projects/$projectSlug/executions'
    | '/o/$organizationSlug/projects/$projectSlug/overview'
    | '/o/$organizationSlug/projects/$projectSlug/settings/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/webhook'
    | '/activate'
    | '/api/manual-runs'
    | '/assets/$'
    | '/test/smoke'
    | '/test/trigger'
    | '/'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/configurations/install'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/daemons/enrollment-tokens'
    | '/api/device-authorizations/poll'
    | '/api/device-authorizations'
    | '/o/$organizationSlug/api-keys'
    | '/o/$organizationSlug/connections'
    | '/o/$organizationSlug/daemons'
    | '/o/$organizationSlug/team'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/o/$organizationSlug/projects'
    | '/o/$organizationSlug/projects/$projectSlug/activity'
    | '/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/o/$organizationSlug/projects/$projectSlug/executions'
    | '/o/$organizationSlug/projects/$projectSlug/overview'
    | '/o/$organizationSlug/projects/$projectSlug/settings/general'
  id:
    | '__root__'
    | '/_shell'
    | '/health'
    | '/webhook'
    | '/_shell/activate'
    | '/api/manual-runs'
    | '/assets/$'
    | '/test/smoke'
    | '/test/trigger'
    | '/_shell/'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/configurations/install'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/daemons/enrollment-tokens'
    | '/api/device-authorizations/poll'
    | '/api/device-authorizations/'
    | '/_shell/o/$organizationSlug/api-keys'
    | '/_shell/o/$organizationSlug/connections'
    | '/_shell/o/$organizationSlug/daemons'
    | '/_shell/o/$organizationSlug/projects'
    | '/_shell/o/$organizationSlug/team'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/_shell/o/$organizationSlug/projects/'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/activity'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/executions'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/overview'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  HealthRoute: typeof HealthRoute
  WebhookRoute: typeof WebhookRoute
  ApiManualRunsRoute: typeof ApiManualRunsRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  TestSmokeRoute: typeof TestSmokeRoute
  TestTriggerRoute: typeof TestTriggerRoute
  AgentExecutionsExecutionIdMcpRoute: typeof AgentExecutionsExecutionIdMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConfigurationsInstallRoute: typeof ApiConfigurationsInstallRoute
  ApiDaemonsDaemonIdRoute: typeof ApiDaemonsDaemonIdRoute
  ApiDaemonsEnrollRoute: typeof ApiDaemonsEnrollRoute
  ApiDaemonsEnrollmentTokensRoute: typeof ApiDaemonsEnrollmentTokensRoute
  ApiDeviceAuthorizationsPollRoute: typeof ApiDeviceAuthorizationsPollRoute
  ApiDeviceAuthorizationsIndexRoute: typeof ApiDeviceAuthorizationsIndexRoute
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute: typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsGithubSetupRoute: typeof ApiIntegrationsGithubSetupRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
  ApiIntegrationsSlackEventsRoute: typeof ApiIntegrationsSlackEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/test/trigger': {
      id: '/test/trigger'
      path: '/test/trigger'
      fullPath: '/test/trigger'
      preLoaderRoute: typeof TestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/smoke': {
      id: '/test/smoke'
      path: '/test/smoke'
      fullPath: '/test/smoke'
      preLoaderRoute: typeof TestSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manual-runs': {
      id: '/api/manual-runs'
      path: '/api/manual-runs'
      fullPath: '/api/manual-runs'
      preLoaderRoute: typeof ApiManualRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/activate': {
      id: '/_shell/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ShellActivateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/device-authorizations/': {
      id: '/api/device-authorizations/'
      path: '/api/device-authorizations'
      fullPath: '/api/device-authorizations/'
      preLoaderRoute: typeof ApiDeviceAuthorizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device-authorizations/poll': {
      id: '/api/device-authorizations/poll'
      path: '/api/device-authorizations/poll'
      fullPath: '/api/device-authorizations/poll'
      preLoaderRoute: typeof ApiDeviceAuthorizationsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daemons/enrollment-tokens': {
      id: '/api/daemons/enrollment-tokens'
      path: '/api/daemons/enrollment-tokens'
      fullPath: '/api/daemons/enrollment-tokens'
      preLoaderRoute: typeof ApiDaemonsEnrollmentTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daemons/enroll': {
      id: '/api/daemons/enroll'
      path: '/api/daemons/enroll'
      fullPath: '/api/daemons/enroll'
      preLoaderRoute: typeof ApiDaemonsEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daemons/$daemonId': {
      id: '/api/daemons/$daemonId'
      path: '/api/daemons/$daemonId'
      fullPath: '/api/daemons/$daemonId'
      preLoaderRoute: typeof ApiDaemonsDaemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/configurations/install': {
      id: '/api/configurations/install'
      path: '/api/configurations/install'
      fullPath: '/api/configurations/install'
      preLoaderRoute: typeof ApiConfigurationsInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-executions/$executionId/mcp': {
      id: '/agent-executions/$executionId/mcp'
      path: '/agent-executions/$executionId/mcp'
      fullPath: '/agent-executions/$executionId/mcp'
      preLoaderRoute: typeof AgentExecutionsExecutionIdMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/events': {
      id: '/api/integrations/slack/events'
      path: '/api/integrations/slack/events'
      fullPath: '/api/integrations/slack/events'
      preLoaderRoute: typeof ApiIntegrationsSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/setup': {
      id: '/api/integrations/github/setup'
      path: '/api/integrations/github/setup'
      fullPath: '/api/integrations/github/setup'
      preLoaderRoute: typeof ApiIntegrationsGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-executions/$executionId/attachments/$attachmentId': {
      id: '/agent-executions/$executionId/attachments/$attachmentId'
      path: '/agent-executions/$executionId/attachments/$attachmentId'
      fullPath: '/agent-executions/$executionId/attachments/$attachmentId'
      preLoaderRoute: typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/o/$organizationSlug/team': {
      id: '/_shell/o/$organizationSlug/team'
      path: '/o/$organizationSlug/team'
      fullPath: '/o/$organizationSlug/team'
      preLoaderRoute: typeof ShellOOrganizationSlugTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/projects': {
      id: '/_shell/o/$organizationSlug/projects'
      path: '/o/$organizationSlug/projects'
      fullPath: '/o/$organizationSlug/projects'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/daemons': {
      id: '/_shell/o/$organizationSlug/daemons'
      path: '/o/$organizationSlug/daemons'
      fullPath: '/o/$organizationSlug/daemons'
      preLoaderRoute: typeof ShellOOrganizationSlugDaemonsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/connections': {
      id: '/_shell/o/$organizationSlug/connections'
      path: '/o/$organizationSlug/connections'
      fullPath: '/o/$organizationSlug/connections'
      preLoaderRoute: typeof ShellOOrganizationSlugConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/api-keys': {
      id: '/_shell/o/$organizationSlug/api-keys'
      path: '/o/$organizationSlug/api-keys'
      fullPath: '/o/$organizationSlug/api-keys'
      preLoaderRoute: typeof ShellOOrganizationSlugApiKeysRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/projects/': {
      id: '/_shell/o/$organizationSlug/projects/'
      path: '/'
      fullPath: '/o/$organizationSlug/projects/'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsIndexRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/overview': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/overview'
      path: '/$projectSlug/overview'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/overview'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/executions': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/executions'
      path: '/$projectSlug/executions'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/executions'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugExecutionsRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/configuration': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
      path: '/$projectSlug/configuration'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/configuration'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/activity': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/activity'
      path: '/$projectSlug/activity'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/activity'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'
      path: '/$projectSlug/settings/general'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/settings/general'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
  }
}

interface ShellOOrganizationSlugProjectsRouteChildren {
  ShellOOrganizationSlugProjectsIndexRoute: typeof ShellOOrganizationSlugProjectsIndexRoute
  ShellOOrganizationSlugProjectsProjectSlugActivityRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
  ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute: typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute: typeof ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute
  ShellOOrganizationSlugProjectsProjectSlugOverviewRoute: typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute: typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
}

const ShellOOrganizationSlugProjectsRouteChildren: ShellOOrganizationSlugProjectsRouteChildren =
  {
    ShellOOrganizationSlugProjectsIndexRoute:
      ShellOOrganizationSlugProjectsIndexRoute,
    ShellOOrganizationSlugProjectsProjectSlugActivityRoute:
      ShellOOrganizationSlugProjectsProjectSlugActivityRoute,
    ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute:
      ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute,
    ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute:
      ShellOOrganizationSlugProjectsProjectSlugExecutionsRoute,
    ShellOOrganizationSlugProjectsProjectSlugOverviewRoute:
      ShellOOrganizationSlugProjectsProjectSlugOverviewRoute,
    ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute:
      ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute,
  }

const ShellOOrganizationSlugProjectsRouteWithChildren =
  ShellOOrganizationSlugProjectsRoute._addFileChildren(
    ShellOOrganizationSlugProjectsRouteChildren,
  )

interface ShellRouteChildren {
  ShellActivateRoute: typeof ShellActivateRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellOOrganizationSlugApiKeysRoute: typeof ShellOOrganizationSlugApiKeysRoute
  ShellOOrganizationSlugConnectionsRoute: typeof ShellOOrganizationSlugConnectionsRoute
  ShellOOrganizationSlugDaemonsRoute: typeof ShellOOrganizationSlugDaemonsRoute
  ShellOOrganizationSlugProjectsRoute: typeof ShellOOrganizationSlugProjectsRouteWithChildren
  ShellOOrganizationSlugTeamRoute: typeof ShellOOrganizationSlugTeamRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActivateRoute: ShellActivateRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellOOrganizationSlugApiKeysRoute: ShellOOrganizationSlugApiKeysRoute,
  ShellOOrganizationSlugConnectionsRoute:
    ShellOOrganizationSlugConnectionsRoute,
  ShellOOrganizationSlugDaemonsRoute: ShellOOrganizationSlugDaemonsRoute,
  ShellOOrganizationSlugProjectsRoute:
    ShellOOrganizationSlugProjectsRouteWithChildren,
  ShellOOrganizationSlugTeamRoute: ShellOOrganizationSlugTeamRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  HealthRoute: HealthRoute,
  WebhookRoute: WebhookRoute,
  ApiManualRunsRoute: ApiManualRunsRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  TestSmokeRoute: TestSmokeRoute,
  TestTriggerRoute: TestTriggerRoute,
  AgentExecutionsExecutionIdMcpRoute: AgentExecutionsExecutionIdMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConfigurationsInstallRoute: ApiConfigurationsInstallRoute,
  ApiDaemonsDaemonIdRoute: ApiDaemonsDaemonIdRoute,
  ApiDaemonsEnrollRoute: ApiDaemonsEnrollRoute,
  ApiDaemonsEnrollmentTokensRoute: ApiDaemonsEnrollmentTokensRoute,
  ApiDeviceAuthorizationsPollRoute: ApiDeviceAuthorizationsPollRoute,
  ApiDeviceAuthorizationsIndexRoute: ApiDeviceAuthorizationsIndexRoute,
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute:
    AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsGithubSetupRoute: ApiIntegrationsGithubSetupRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
  ApiIntegrationsSlackEventsRoute: ApiIntegrationsSlackEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
